#%RAML 1.0 NamedExample
value:
-
  ID: 1
  Name: John
  Type: Business
  Address: "#73, highStreet,London LN789"
  Airmiles: 9000
  CreationDate: 2010-01-01T00:00:00Z
  
-

  ID: 1
  Name: Lewis
  Type: Personal
  Address: "#99, CherryTrees,London LN823"
  Airmiles: 5000
  CreationDate: 2010-05-08T00:00:00Z